package javaproject.models;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * @author Ahmad
 * @version 1.0
 * 
 *          POJO (plain old java object) for the UserAccount database. The
 *          primary key generated by JPA is used for mapping in both the
 *          Location Registry and Conveyance Registry (as foreign key) 
 */
@Entity
@Table(name = "Project_User_Accounts")
@NamedQuery(name = "UserAccount.findByUserNamePassword", query = "select u from UserAccount u where u.uName=?1 and u.password=?2")
public class UserAccount {

	@Id
	@GeneratedValue(strategy = GenerationType.TABLE) // check Gen type of Primary key
	@Column(name = "Account_Id")
	private int accountid;

	@Column(name = "First_name")
	private String fName;

	@Column(name = "Last_name")
	private String lName;

	@Column(name = "UserName")
	private String uName;

	@Column(name = "Password")
	private String password;

	@Column(name = "Email")
	private String email;

	@OneToMany(mappedBy = "useraccount")
	private List<LocationRegistry> locationregistry = new ArrayList<LocationRegistry>();

	@OneToMany(mappedBy = "useraccount")
	private List<ConveyanceRegistry> conveyanceregistry = new ArrayList<ConveyanceRegistry>();

	public UserAccount() {
		super();
		// TODO Auto-generated constructor stub
	}

	// Id and LocationRegistry not included in constructor
	public UserAccount(String fName, String lName, String uName, String password, String email) {
		super();

		this.fName = fName;
		this.lName = lName;
		this.uName = uName;
		this.password = password;
		this.email = email;
	}

	public List<LocationRegistry> getLocationregistry() {
		return locationregistry;
	}

	public void setLocationregistry(List<LocationRegistry> locationregistry) {
		this.locationregistry = locationregistry;
	}

	public List<ConveyanceRegistry> getConveyanceregistry() {
		return conveyanceregistry;
	}

	public void setConveyanceregistry(List<ConveyanceRegistry> conveyanceregistry) {
		this.conveyanceregistry = conveyanceregistry;
	}

	public String getfName() {
		return fName;
	}

	public void setfName(String fName) {
		this.fName = fName;
	}

	public String getlName() {
		return lName;
	}

	public void setlName(String lName) {
		this.lName = lName;
	}

	public String getuName() {
		return uName;
	}

	public void setuName(String uName) {
		this.uName = uName;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Override
	public String toString() {
		return "UserAccount [accountid=" + accountid + ", fName=" + fName + ", lName=" + lName + ", uName=" + uName
				+ ", password=" + password + ", email=" + email + "]";
	}

}
